name: gha_example:GitHub Action exercise 

# Szablon workflow: Miejsca oznaczone "#" naley uzupełnić 

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  build:
    # Definicja systemu do instalacji na wźle roboczym 
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      # Instalacja środowiska Docker + Buildx
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      # Logowanie do Dockerhub-a
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # Budowa obrazu dla dwóch architektur sprzętowych 
      # oraz przesłanie do własnego repo na Dockerhub
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64/v8,linux/amd64 
          context: .
          file: ./Dockerfile_prod
          push: true
          tags: |
            v17v3/lab10:ghlab10example
      